ci(docker): more platform, matrix(disabled), build test

diff --git a/.github/workflows/publish-docker-image.yml b/.github/workflows/publish-docker-image.yml
--- a/.github/workflows/publish-docker-image.yml
+++ b/.github/workflows/publish-docker-image.yml
@@ -1,134 +1,53 @@
-name: Publish Docker Image
-
-on:
-  workflow_dispatch:
-  release:
-    types: [prereleased, released]
-  schedule:
-    - cron: "0 16 * * *"
-  # push:
-  #   branches:
-  #     - "**"
-  #   tags:
-  #     - "v*.*.*"
-  # pull_request:
-  #   branches:
-  #     - "main"
-
-jobs:
-  publish-docker-image:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          submodules: 'recursive'
-
-      - name: Prepare Tag
-        # Borrowed from daeuniverse/dae
-        id: prep
-        env:
-          REF: ${{ github.ref }}
-        run: |
-          if [[ "$REF" == "refs/tags/v"* ]]; then
-            tag=$(git describe --tags $(git rev-list --tags --max-count=1))
-            tag=${tag:1}
-          else
-            tag=$(git log -1 --format="%cd" --date=short | sed s/-//g)
-          fi
-          echo "IMAGE=daeuniverse/daed" >> $GITHUB_OUTPUT
-          echo "TAG=$tag" >> $GITHUB_OUTPUT
-
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          # list of Docker images to use as base name for tags
-          images: |
-            ${{ github.repository }}
-            ghcr.io/${{ github.repository }}
-            quay.io/${{ github.repository }}
-          # generate Docker tags based on the following events/attributes
-          # nightly, YYYYMMDD, on:push:branch, pr-NO., *.*.*
-          tags: |
-            type=schedule
-            type=schedule,pattern={{date 'YYYYMMDD'}}
-            type=ref,event=branch
-            type=ref,event=pr
-            type=semver,pattern={{version}}
-          flavor: |
-            latest=auto
-            prefix=
-            suffix=
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        # id: buildx
-
-      - name: Login to Docker Hub
-        # if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Login to ghcr.io
-        # if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Login to quay.io
-        # if: github.event_name != 'pull_request'
-        uses: docker/login-action@v3
-        with:
-          registry: quay.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.QUAY_PASS }}
-
-      - name: Build and push
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          build-args: DAED_VERSION=${{ steps.prep.outputs.TAG }}
-          # builder: ${{ steps.buildx.outputs.name }}
-          platforms: linux/amd64,linux/arm64,linux/ppc64le
-          push: true
-          # push: ${{ github.event_name != 'pull_request' }}
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-
-
 # name: Publish Docker Image
 #
 # on:
 #   workflow_dispatch:
-#   release:
-#     types: [prereleased, released]
-#   # schedule:
-#   #   - cron: "0 10 * * *"
-#   # push:
-#   #   branches:
-#   #     - "**"
-#   #   tags:
-#   #     - "v*.*.*"
-#   # pull_request:
-#   #   branches:
-#   #     - "main"
+#   push:
+#     branches:
+#       - "main"
+#   # release:
+#   #   types: [prereleased,released]
+#
+# env:
+#   REGISTRY_IMAGE: daeuniverse/daed
+#
 #
 # jobs:
-#   publish-docker-image:
+#
+#   build-web:
 #     runs-on: ubuntu-latest
 #     steps:
-#       - name: Checkout
-#         uses: actions/checkout@v4
+#       - uses: actions/checkout@v3
+#         # with:
+#         #   submodules: 'recursive'
+#
+#       - uses: pnpm/action-setup@v2
+#         with:
+#           version: latest
+#
+#       - uses: actions/setup-node@v3
+#         with:
+#           cache: pnpm
+#           node-version: latest
+#
+#       - name: Build
+#         run: |
+#           pnpm install
+#           pnpm build
+#
+#       - name: Upload artifact - web
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: web
+#           path: dist
+#
+#
+#
+#   publish-docker-image:
+#     runs-on: ubuntu-latest
+#
+#     steps:
+#       - uses: actions/checkout@v4
 #         with:
 #           submodules: 'recursive'
 #
@@ -138,6 +57,15 @@ jobs:
 #         env:
 #           REF: ${{ github.ref }}
 #         run: |
+#           DIR="$(pwd)/dist/"
+#           if [ -d "$DIR" ]; then
+#             ### Take action if $DIR exists ###
+#             echo "Installing config files in ${DIR}..."
+#           else
+#             ###  Control will jump here if $DIR does NOT exists ###
+#             echo "Error: ${DIR} not found. Can not continue."
+#             exit 1
+#           fi
 #           if [[ "$REF" == "refs/tags/v"* ]]; then
 #             tag=$(git describe --tags $(git rev-list --tags --max-count=1))
 #             tag=${tag:1}
@@ -147,69 +75,186 @@ jobs:
 #           echo "IMAGE=daeuniverse/daed" >> $GITHUB_OUTPUT
 #           echo "TAG=$tag" >> $GITHUB_OUTPUT
 #
-#       - name: Docker meta
-#         id: meta
-#         uses: docker/metadata-action@v5
-#         with:
-#           # list of Docker images to use as base name for tags
-#           images: |
-#             huangqizigailee/daed-test-test
-# #             ghcr.io/${{ github.repository }}
-# #             quay.io/${{ github.repository }}
-#           # generate Docker tags based on the following events/attributes
-#           tags: |
-#             type=schedule
-#             type=ref,event=branch
-#             type=ref,event=pr
-#             type=semver,pattern={{version}}
-#             type=semver,pattern={{major}}.{{minor}}
-#             type=semver,pattern={{major}}
-#             type=sha
-#           flavor: |
-#             latest=auto
-#             prefix=
-#             suffix=
-#
 #       - name: Set up QEMU
 #         uses: docker/setup-qemu-action@v3
 #
 #       - name: Set up Docker Buildx
 #         uses: docker/setup-buildx-action@v3
-#         # id: buildx
+#         id: buildx
 #
 #       - name: Login to Docker Hub
-#         # if: github.event_name != 'pull_request'
 #         uses: docker/login-action@v3
 #         with:
 #           username: ${{ secrets.DOCKERHUB_USERNAME }}
-#           password: ${{ secrets.DOCKERHUB_PASS }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
 #
-#       # - name: Login to ghcr.io
-#       #   # if: github.event_name != 'pull_request'
-#       #   uses: docker/login-action@v3
-#       #   with:
-#       #     registry: ghcr.io
-#       #     username: ${{ github.actor }}
-#       #     password: ${{ secrets.GITHUB_TOKEN }}
+#       - name: Login to ghrc.io
+#         uses: docker/login-action@v3
+#         with:
+#           registry: ghcr.io
+#           username: ${{ github.actor }}
+#           password: ${{ secrets.GITHUB_TOKEN }}
 #
 #       # - name: Login to quay.io
-#       #   # if: github.event_name != 'pull_request'
 #       #   uses: docker/login-action@v3
 #       #   with:
 #       #     registry: quay.io
 #       #     username: ${{ github.repository_owner }}
 #       #     password: ${{ secrets.QUAY_PASS }}
 #
-#       - name: Build and push
+#       - name: Build image
 #         uses: docker/build-push-action@v5
 #         with:
 #           context: .
 #           build-args: DAED_VERSION=${{ steps.prep.outputs.TAG }}
-#           # builder: ${{ steps.buildx.outputs.name }}
-#           platforms: linux/amd64,linux/arm64,linux/ppc64le
+#           builder: ${{ steps.buildx.outputs.name }}
+#           file: publish.Dockerfile
+#           target: this-image-is-built-for-final-publish-with-support-of-multiple-platforms
+#           platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v5,linux/arm/v7,linux/arm64/v8 #,linux/mips64le,linux/ppc64e,linux/s390x
 #           push: true
-#           # push: ${{ github.event_name != 'pull_request' }}
-#           tags: ${{ steps.meta.outputs.tags }}
-#           labels: ${{ steps.meta.outputs.labels }}
+#           tags: |
+#             ${{ github.repository }}:latest
+#             ${{ github.repository }}:${{ steps.prep.outputs.TAG }}
+#             ghcr.io/${{ github.repository }}:latest
+#             ghcr.io/${{ github.repository }}:${{ steps.prep.outputs.TAG }}
+# #             quay.io/${{ github.repository }}:latest
+# #             quay.io/${{ github.repository }}:${{ steps.prep.outputs.TAG }}
 #           cache-from: type=gha
 #           cache-to: type=gha,mode=max
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+name: Publish Docker Image
+
+on:
+  workflow_dispatch:
+  push:
+    branches:
+      - "main"
+  # release:
+  #   types: [prereleased,released]
+
+env:
+  REGISTRY_IMAGE: daeuniverse/daed
+
+
+jobs:
+
+  build-web:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        # with:
+        #   submodules: 'recursive'
+
+      - uses: pnpm/action-setup@v2
+        with:
+          version: latest
+
+      - uses: actions/setup-node@v3
+        with:
+          cache: pnpm
+          node-version: latest
+
+      - name: Build
+        run: |
+          pnpm install
+          pnpm build
+
+      - name: Upload artifact - web
+        uses: actions/upload-artifact@v3
+        with:
+          name: web
+          path: dist
+
+
+
+  publish-docker-image:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+
+      - name: Prepare Tag
+        # Borrowed from daeuniverse/dae
+        id: prep
+        env:
+          REF: ${{ github.ref }}
+        run: |
+          DIR="$(pwd)/dist/"
+          if [ -d "$DIR" ]; then
+            ### Take action if $DIR exists ###
+            echo "Installing config files in ${DIR}..."
+          else
+            ###  Control will jump here if $DIR does NOT exists ###
+            echo "Error: ${DIR} not found. Can not continue."
+            exit 1
+          fi
+          if [[ "$REF" == "refs/tags/v"* ]]; then
+            tag=$(git describe --tags $(git rev-list --tags --max-count=1))
+            tag=${tag:1}
+          else
+            tag=$(git log -1 --format="%cd" --date=short | sed s/-//g)
+          fi
+          echo "IMAGE=huangqizigailee/daed" >> $GITHUB_OUTPUT
+          echo "TAG=$tag" >> $GITHUB_OUTPUT
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        id: buildx
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASS }}
+
+      - name: Login to ghrc.io
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      # - name: Login to quay.io
+      #   uses: docker/login-action@v3
+      #   with:
+      #     registry: quay.io
+      #     username: ${{ github.repository_owner }}
+      #     password: ${{ secrets.QUAY_PASS }}
+
+      - name: Build image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          build-args: DAED_VERSION=${{ steps.prep.outputs.TAG }}
+          builder: ${{ steps.buildx.outputs.name }}
+          file: publish.Dockerfile
+          target: this-image-is-built-for-final-publish-with-support-of-multiple-platforms
+          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v5,linux/arm/v7,linux/arm64/v8 #,linux/mips64le,linux/ppc64e,linux/s390x
+          push: true
+          tags: |
+            ${{ steps.prep.outputs.IMAGE }}:latest
+            ${{ steps.prep.outputs.IMAGE }}:${{ steps.prep.outputs.TAG }}
+            ghcr.io/${{ github.repository }}:latest
+            ghcr.io/${{ github.repository }}:${{ steps.prep.outputs.TAG }}
+#             quay.io/${{ github.repository }}:latest
+#             quay.io/${{ github.repository }}:${{ steps.prep.outputs.TAG }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
